name       : 0ad
version    : 0.0.25a
release    : 31
source     :
    - https://releases.wildfiregames.com/0ad-0.0.25-alpha-unix-build.tar.xz : 592eab37c1a1588e87b1f22d328fd6ca84ba47f32219f9e0fc4bbf67e745430f
license    :
    - BSD-2-Clause
    - CC-BY-SA-3.0 # Mods
    - GPL-2.0-or-later
    - ISC # Encryption
    - MIT
    - Zlib # tinygettext third party
component  : games.strategy
summary    : 0 A.D. is a free, open-source, cross-platform real-time strategy game of ancient warfare
description: |
    0 A.D. is a free, open-source, cross-platform real-time strategy game of ancient warfare.
builddeps  :
    - pkgconfig(fmt)
    - pkgconfig(gl)
    - pkgconfig(gloox)
    - pkgconfig(gnutls)
    - pkgconfig(icu-io)
    - pkgconfig(libcurl)
    - pkgconfig(libenet)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libsodium)
    - pkgconfig(libtiff-4)
    - pkgconfig(miniupnpc)
    - pkgconfig(mozjs-78)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - libboost-devel
    - wxwidgets-devel
rundeps    :
    - 0ad-data
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-startup-class-to-desktop-file-so-we-can-provide-.patch
    %patch -p1 < $pkgfiles/0ad-rpath.patch
    %patch -p1 < $pkgfiles/0ad-mozjs-incompatible.patch
    cd build/workspaces
    sed -i '3,6d' update-workspaces.sh
    ./update-workspaces.sh \
        --bindir=/usr/bin \
        --datadir=/usr/share/0ad/data \
        --disable-atlas \
        --libdir=%libdir%/0ad \
        --with-system-mozjs \
        --without-nvtt
build      : |
    %make -C build/workspaces/gcc
install    : |
    install -dm00644 $installdir/%libdir%/0ad/
    install -dm00644 $installdir/usr/share/0ad/data/
    install -Dm00755 binaries/system/pyrogenesis $installdir/usr/bin/pyrogenesis
    install -Dm00755 binaries/system/*.so $installdir/%libdir%/0ad/
    cp -R binaries/data/l10n/ $installdir/usr/share/0ad/data/
    chmod 00644 $installdir/usr/share/0ad/data/*
    install -Dm00755 build/resources/0ad.sh $installdir/usr/bin/0ad
    install -Dm00644 build/resources/0ad.desktop $installdir/usr/share/applications/0ad.desktop
    install -Dm00644 build/resources/0ad.png $installdir/usr/share/pixmaps/0ad.png
